name: budgetbuddy_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  get_it: ^8.0.3
  auto_size_text: ^3.0.0
  cloud_functions: ^6.0.4
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/sonic.png
    - assets/images/alden.jpg
